name: Construction image Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Construire l'image Docker
        run: docker build -t piphocos:ci .
